[server]
headless = true
port = 8501
enableCORS = false

[browser]
gatherUsageStats = false

[theme]
primaryColor = "#ff8c00"
backgroundColor = "#000000"
secondaryBackgroundColor = "#0a0a0a"
textColor = "#dddddd"
font = "monospace"
